[workspace]
authors = ["jarvis65536 <jarvis65536@gmail.com>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "ros2bookcode"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
# 工作空间构建
build = "colcon build"

[dependencies]
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-joint-state-publisher = ">=2.3.0,<3.0.0"
ros-jazzy-robot-state-publisher = ">=3.0.0,<3.8.0"
ros-jazzy-xacro = ">=2.1.0,<2.2.0"
colcon-ros = ">=0.5.0,<0.6"
urdfdom = ">=4.0.1,<5"
ros-jazzy-ros-gz-sim = ">=1.0.18,<2"
ros-jazzy-ros-gz-bridge = ">=1.0.18,<2"
ros-jazzy-gz-ros2-control = ">=1.2.17,<2"
ros-jazzy-ros2-control = ">=4.42.1,<5"
ros-jazzy-ros2-control-cmake = ">=0.3.0,<0.4"
ros-jazzy-ros2-controllers = ">=4.36.0,<5"
ros-jazzy-controller-interface = ">=4.42.1,<5"
ros-jazzy-controller-manager = ">=4.42.1,<5"

[activation]
# Source ROS2 shell configuration for tab completion
# scripts = ["auto_complete.bash"]
# 上述方法暂时无法解决自动激活补全功能，仍需要在 pixi env 中手动执行以上脚本

# Set LIBRARY_PATH to include pixi environment libraries for linking
env = { LIBRARY_PATH = "$CONDA_PREFIX/lib${LIBRARY_PATH:+:$LIBRARY_PATH}" }
